version: "3"
services:
  mongo_child:
    image: mongo
    volumes:
      - ./data/mongodb_child:/data/db
    ports:
      - "27011:27017"

  mongo_colous:
    image: mongo
    volumes:
      - ./data/mongodb_colaus:/data/db
    ports:
      - "27012:27017"

  mongo_h3africa:
    image: mongo
    volumes:
      - ./data/mongodb_h3africa:/data/db
    ports:
      - "27013:27017"

  postgres:
    environment:
      - PGDATA=/search-db
      - POSTGRES_USER=search
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=search
    image: postgres:9.6-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  prestoapp:
    build: ./presto_service
    ports:
      - "8080:8080"
    links:
      - mongo
      - postgres
    depends_on:
      - mongo
      - postgres