version: "3"
services:
  mongo:
    container_name: local_mongo
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  postgres:
    environment:
      - PGDATA=/search-db
      - POSTGRES_USER=search
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=search
    hostname: search-db
    container_name: search-db
    image: postgres:9.6-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  prestoapp:
    container_name: prestoapp
    build: ./presto_service
    ports:
      - "8080:8080"
    links:
      - mongo
      - postgres
    depends_on:
      - mongo
      - postgres

  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    depends_on:
      - mongo
    links:
      - mongo
